import Foundation

/// 5 家非 jsonHooks 的最简转发器内容。
///
/// 这些 plugin / extension / hook 脚本的工作模式：
/// 1. 由各家 CLI（OpenCode/Hermes/Pi/OpenClaw）在收到 hook 事件时调用；
/// 2. 把事件 payload 从 stdin/参数 转成 JSON；
/// 3. 调起 PingIslandBridge 把 envelope 投递到 lite 的 socket。
///
/// 主仓里这些 plugin 是几百到上千行的"高保真版"，做了终端透视、tmux、iTerm session 检测、IDE 句柄等等。
/// Lite 阶段只要让 envelope 能进到 bridge → lite，菜单栏吉祥物状态机就能动起来，足够。
enum PluginSources {

    static let pingIslandMarker = "Ping Island managed integration"

    // MARK: - Public dispatch

    /// 单文件 plugin 内容（OpenCode）。
    static func source(for provider: HookInstaller.Provider, bridgePath: String) -> String {
        switch provider {
        case .opencode: return openCodePluginJS(bridgePath: bridgePath)
        default:        return ""
        }
    }

    /// 目录式 plugin / extension / hook 的文件清单：相对路径 → 文件内容。
    static func directoryFiles(for provider: HookInstaller.Provider, bridgePath: String) -> [String: String] {
        switch provider {
        case .hermes:   return hermesFiles(bridgePath: bridgePath)
        case .pi:       return piFiles(bridgePath: bridgePath)
        case .openclaw: return openClawFiles(bridgePath: bridgePath)
        default:        return [:]
        }
    }

    // MARK: - OpenCode plugin file

    /// OpenCode plugin（CommonJS）。OpenCode 启动时会自动 import 此文件并调用 `default` export。
    /// 这里订阅几个关键钩子 → 调 PingIslandBridge 透传。
    private static func openCodePluginJS(bridgePath: String) -> String {
        let cmdJSON = bridgeArgsJSON(provider: .opencode, bridgePath: bridgePath)
        return """
        // \(pingIslandMarker): opencode
        // Generated by AgentBeacon. Reinstall from Island menu to refresh.

        const { spawn } = require("node:child_process");
        const BRIDGE_ARGS = \(cmdJSON);

        function dispatch(eventType, payload) {
          try {
            const envelope = {
              eventType,
              client: { kind: "opencode", name: "OpenCode", origin: "cli" },
              payload: payload ?? {},
              timestamp: new Date().toISOString()
            };
            const child = spawn(BRIDGE_ARGS[0], BRIDGE_ARGS.slice(1), {
              stdio: ["pipe", "ignore", "ignore"],
              detached: true
            });
            child.stdin.write(JSON.stringify(envelope));
            child.stdin.end();
            child.unref();
          } catch (err) {
            // 静默失败：lite 接收不到事件不应影响 OpenCode 本体。
          }
        }

        module.exports = async function pingIslandPlugin(api) {
          api?.on?.("session.start",       (e) => dispatch("SessionStart", e));
          api?.on?.("session.end",         (e) => dispatch("SessionEnd", e));
          api?.on?.("user.message.submit", (e) => dispatch("UserPromptSubmit", e));
          api?.on?.("tool.before",         (e) => dispatch("PreToolUse", e));
          api?.on?.("tool.after",          (e) => dispatch("PostToolUse", e));
          api?.on?.("permission.request",  (e) => dispatch("PermissionRequest", e));
          api?.on?.("agent.stop",          (e) => dispatch("Stop", e));
        };
        """
    }

    // MARK: - Hermes plugin directory

    /// Hermes plugin（Python，Hermes CLI 启动时自动 discover）。
    private static func hermesFiles(bridgePath: String) -> [String: String] {
        let argsJSON = bridgeArgsJSON(provider: .hermes, bridgePath: bridgePath)
        let pluginYAML = """
        # \(pingIslandMarker): hermes
        name: ping_island
        version: 1.0.0
        description: Forward Hermes hook events to AgentBeacon
        provides_hooks:
          - on_session_start
          - on_session_end
          - pre_llm_call
          - post_llm_call
          - pre_tool_call
          - post_tool_call
        """
        let initPy = """
        # \(pingIslandMarker): hermes
        \"\"\"Hermes plugin generated by AgentBeacon.\"\"\"
        import json, os, subprocess
        BRIDGE_ARGS = json.loads(r'''\(argsJSON)''')

        def _dispatch(event_type, payload):
            try:
                envelope = {
                    "eventType": event_type,
                    "client": {"kind": "hermes", "name": "Hermes", "origin": "cli"},
                    "payload": payload or {},
                }
                proc = subprocess.Popen(
                    BRIDGE_ARGS,
                    stdin=subprocess.PIPE,
                    stdout=subprocess.DEVNULL,
                    stderr=subprocess.DEVNULL,
                    close_fds=True,
                )
                proc.stdin.write(json.dumps(envelope).encode("utf-8"))
                proc.stdin.close()
            except Exception:
                pass

        def register(ctx):
            ctx.register_hook("on_session_start",  lambda e: _dispatch("SessionStart", e))
            ctx.register_hook("on_session_end",    lambda e: _dispatch("SessionEnd", e))
            ctx.register_hook("pre_llm_call",      lambda e: _dispatch("UserPromptSubmit", e))
            ctx.register_hook("pre_tool_call",     lambda e: _dispatch("PreToolUse", e))
            ctx.register_hook("post_tool_call",    lambda e: _dispatch("PostToolUse", e))
            ctx.register_hook("post_llm_call",     lambda e: _dispatch("Stop", e))
        """
        return [
            "plugin.yaml":  pluginYAML,
            "__init__.py":  initPy,
        ]
    }

    // MARK: - Pi extension directory

    /// Pi Agent extension（TypeScript，Pi 启动时由内置 loader 装载）。
    private static func piFiles(bridgePath: String) -> [String: String] {
        let argsJSON = bridgeArgsJSON(provider: .pi, bridgePath: bridgePath)
        let indexTS = """
        // \(pingIslandMarker): pi
        // Generated by AgentBeacon. Reinstall from Island menu to refresh.

        import { spawn } from "node:child_process";
        const BRIDGE_ARGS = \(argsJSON) as string[];

        function dispatch(eventType: string, payload: unknown) {
          try {
            const envelope = {
              eventType,
              client: { kind: "pi", name: "Pi Agent", origin: "cli" },
              payload: payload ?? {},
              timestamp: new Date().toISOString(),
            };
            const child = spawn(BRIDGE_ARGS[0], BRIDGE_ARGS.slice(1), {
              stdio: ["pipe", "ignore", "ignore"],
              detached: true,
            });
            child.stdin.write(JSON.stringify(envelope));
            child.stdin.end();
            child.unref();
          } catch {
            /* silent */
          }
        }

        export default function register(api: any) {
          api?.on?.("session:start",       (e: any) => dispatch("SessionStart", e));
          api?.on?.("session:end",         (e: any) => dispatch("SessionEnd", e));
          api?.on?.("prompt:submit",       (e: any) => dispatch("UserPromptSubmit", e));
          api?.on?.("tool:pre",            (e: any) => dispatch("PreToolUse", e));
          api?.on?.("tool:post",           (e: any) => dispatch("PostToolUse", e));
          api?.on?.("permission:request",  (e: any) => dispatch("PermissionRequest", e));
          api?.on?.("agent:stop",          (e: any) => dispatch("Stop", e));
        }
        """
        return ["index.ts": indexTS]
    }

    // MARK: - OpenClaw hook directory

    /// OpenClaw internal hook（TS handler + markdown 头）。Hook 会被 openclaw.json 启用后才触发。
    private static func openClawFiles(bridgePath: String) -> [String: String] {
        let argsJSON = bridgeArgsJSON(provider: .openclaw, bridgePath: bridgePath)
        let hookMD = """
        ---
        name: ping-island-openclaw
        description: "Forward OpenClaw internal hook events to AgentBeacon"
        metadata: { "openclaw": { "events": ["command", "message", "session"] } }
        ---

        <!-- \(pingIslandMarker): openclaw -->
        # AgentBeacon OpenClaw Hook
        Generated by AgentBeacon. Reinstall from Island menu to refresh.
        """
        let handlerTS = """
        // \(pingIslandMarker): openclaw
        import { spawn } from "node:child_process";
        const BRIDGE_ARGS = \(argsJSON) as string[];

        function dispatch(eventType: string, payload: unknown) {
          try {
            const envelope = {
              eventType,
              client: { kind: "openclaw", name: "OpenClaw", origin: "gateway" },
              payload: payload ?? {},
              timestamp: new Date().toISOString(),
            };
            const child = spawn(BRIDGE_ARGS[0], BRIDGE_ARGS.slice(1), {
              stdio: ["pipe", "ignore", "ignore"],
              detached: true,
            });
            child.stdin.write(JSON.stringify(envelope));
            child.stdin.end();
            child.unref();
          } catch {
            /* silent */
          }
        }

        export default async function handler(event: any) {
          const key = `${event?.type ?? ""}:${event?.action ?? ""}`;
          // 把内部多种事件归并成 Claude-compatible 大类，方便 lite 状态机消化。
          const claudeEvent = (() => {
            switch (key) {
              case "command:new":          return "SessionStart";
              case "message:received":     return "UserPromptSubmit";
              case "message:sent":         return "Notification";
              case "command:stop":         return "Stop";
              case "session:compact:before":
              case "session:compact:after":return "PreCompact";
              default:                     return "PostToolUse";
            }
          })();
          dispatch(claudeEvent, event);
        }
        """
        return [
            "HOOK.md":     hookMD,
            "handler.ts":  handlerTS,
        ]
    }

    // MARK: - Helpers

    /// 把 bridge 完整命令拼成 JSON 数组字符串，方便 JS / Python / TS 直接 require/import 后 spawn 用。
    private static func bridgeArgsJSON(provider: HookInstaller.Provider, bridgePath: String) -> String {
        let parts: [String] = [bridgePath, "--source", provider.bridgeSourceArgument]
            + provider.bridgeExtraArguments
        let data = (try? JSONSerialization.data(withJSONObject: parts, options: [])) ?? Data("[]".utf8)
        return String(data: data, encoding: .utf8) ?? "[]"
    }
}
